apiVersion: v1
kind: Secret
metadata:
  name: harbor-oci-creds
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {"auths":{"harbor.itcs.local":{"username":"admin","password":"Harbor12345"}}}
