apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "podinfo.fullname" . }}
  labels:
    {{- include "podinfo.labels" . | nindent 4 }}
data:
  UI_COLOR: {{ .Values.ui.color | quote }}
  UI_MESSAGE: {{ .Values.ui.message | quote }}
