apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "podinfo.fullname" . }}
  labels:
    {{- include "podinfo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "podinfo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "podinfo.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: podinfo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - ./podinfo
            - --port={{ .Values.service.port }}
            - --grpc-port={{ .Values.service.grpcPort }}
            - --level=info
          env:
            - name: PODINFO_UI_COLOR
              valueFrom:
                configMapKeyRef:
                  name: {{ include "podinfo.fullname" . }}
                  key: UI_COLOR
            - name: PODINFO_UI_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "podinfo.fullname" . }}
                  key: UI_MESSAGE
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.service.grpcPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
